apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: sample-ace-project
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-AMYG-BQ2E4U
    use: CloudPakForIntegrationProduction
  pod:
    containers:
      runtime:
        image: "us.icr.io/cp4i-gse-poc/sample-ace-project:7efd5107f2d64331c9bb01e4941b28376a2969ad"
    imagePullSecrets:
      - name: ibm-cr-pull-secret
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 11.0.0
