apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: sample-ace-project
spec:
  designerFlowsOperationMode: disabled
  license:
    accept: true
    license: L-AMYG-BQ2E4U
    use: CloudPakForIntegrationProduction
  pod:
    containers:
      runtime:
          image: "us.icr.io/cp4i-gse-poc/sample-ace-project:96e4217d8f9de815e27a6e48560651b629d100a6"
    imagePullSecrets:
      - name: ibm-cr-pull-secret
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  version: 11.0.0
